"""empty message

Revision ID: 5adf56e2028d
Revises: 1d47c89f9bfb
Create Date: 2026-08-08 21:58:54.902750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adf56e2028d'
down_revision = '1d47c89f9bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('character_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('character_planet_id_fkey', 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###
